"""Canonical English URL slugs for the static site."""

from __future__ import annotations

from pathlib import Path

# All published pages (English slug paths under /he/, /en/, and /es/)
CANONICAL_SLUGS: list[str] = [
    "about",
    "building-automation",
    "power-meters-control",
    "products",
    "contact",
    "quality-assurance",
    "product-comparison",
    "transfer-switch-drawings",
    "bms-certifications",
    "elnet-certifications",
    "plc-ddc-controllers",
    "parking-control",
    "plumbing-control",
    "flood-detection-systems",
    "flooding-sensor",
    "bms-scada-software",
    "transfer-switches",
    "power-factor-control",
    "smart-parking",
    "co-gas-monitoring",
    "power-quality-analyzers",
    "energy-meters",
    "electrical-meters",
    "elnet-billing-software",
    "public-buildings",
    "hospitals",
    "hotels",
    "universities",
    "museums",
    "shopping-malls",
    "industrial-hi-tech",
    "pharmaceutical-clean-rooms",
    "uniart-software",
    "uniweb-software",
    "digipoint-controller",
    "veropoint-controller",
    "superbrain-controller",
    "superbrain-dr-controller",
    "superbrain-fc-controller",
    "elnet-mc-1-meter",
    "elnet-mc-2-meter",
    "elnet-mc-8-meter",
    "elnet-mc-12-meter",
    "elnet-co-transfer-switch",
    "elnet-cod-transfer-switch",
    "elnet-pfc-controller",
    "elnet-ltc-controller",
    "elnet-ltc10-controller",
    "elnet-va-meter",
    "elnet-vip-meter",
    "elnet-pic-meter",
    "elnet-lte-meter",
    "elnet-lt-meter",
    "elnet-ltp-meter",
    "elnet-pq-gr-meter",
    "elnet-xp-controller",
]

CANONICAL_TITLES_EN: dict[str, str] = {
    "about": "About",
    "building-automation": "Building Automation",
    "power-meters-control": "Power Meters & Control",
    "products": "Products",
    "contact": "Contact",
    "quality-assurance": "Quality Assurance",
    "product-comparison": "Product Comparison",
    "transfer-switch-drawings": "Transfer Switch Sketches",
    "bms-certifications": "BMS Certifications",
    "elnet-certifications": "ElNet Certifications",
    "plc-ddc-controllers": "PLC & DDC Controllers",
    "parking-control": "Parking Control",
    "plumbing-control": "Plumbing Control",
    "flood-detection-systems": "Flood Detection Systems",
    "flooding-sensor": "Flooding Sensor",
    "bms-scada-software": "BMS / SCADA Software",
    "transfer-switches": "Transfer Switches",
    "power-factor-control": "Power Factor Control",
    "smart-parking": "Smart Parking",
    "co-gas-monitoring": "CO Gas Monitoring",
    "power-quality-analyzers": "Power Quality Analyzers",
    "energy-meters": "Energy Meters",
    "electrical-meters": "Electrical Meters",
    "elnet-billing-software": "ElNet Billing Software",
    "public-buildings": "Public Buildings",
    "hospitals": "Hospitals",
    "hotels": "Hotels",
    "universities": "Universities",
    "museums": "Museums",
    "shopping-malls": "Shopping Malls",
    "industrial-hi-tech": "Industrial & Hi-Tech",
    "pharmaceutical-clean-rooms": "Pharmaceutical & Clean Rooms",
    "uniart-software": "UniArt Software",
    "uniweb-software": "UniWeb Software",
    "digipoint-controller": "DigiPoint Controller",
    "veropoint-controller": "VeroPoint Controller",
    "superbrain-controller": "SuperBrain Controller",
    "superbrain-dr-controller": "SuperBrain DR Controller",
    "superbrain-fc-controller": "SuperBrain FC Controller",
    "elnet-mc-1-meter": "ElNet MC-1 Meter",
    "elnet-mc-2-meter": "ElNet MC-2 Meter",
    "elnet-mc-8-meter": "ElNet MC-8 Meter",
    "elnet-mc-12-meter": "ElNet MC-12 Meter",
    "elnet-co-transfer-switch": "ElNet CO Transfer Switch",
    "elnet-cod-transfer-switch": "ElNet COD Transfer Switch",
    "elnet-pfc-controller": "ElNet PFC Controller",
    "elnet-ltc-controller": "ElNet LTC Controller",
    "elnet-ltc10-controller": "ElNet LTC10 Controller",
    "elnet-va-meter": "ElNet VA Meter",
    "elnet-vip-meter": "ElNet VIP Meter",
    "elnet-pic-meter": "ElNet PIC Meter",
    "elnet-lte-meter": "ElNet LTE Meter",
    "elnet-lt-meter": "ElNet LT Meter",
    "elnet-ltp-meter": "ElNet LTP Meter",
    "elnet-pq-gr-meter": "ElNet PQ/GR Meter",
    "elnet-xp-controller": "ElNet XP Controller",
}

CANONICAL_TITLES_ES: dict[str, str] = {
    "about": "Nosotros",
    "building-automation": "Automatización de edificios",
    "power-meters-control": "Medidores y control eléctrico",
    "products": "Productos",
    "contact": "Contacto",
    "quality-assurance": "Garantía de calidad",
    "product-comparison": "Comparación de productos",
    "transfer-switch-drawings": "Esquemas de interruptores de transferencia",
    "bms-certifications": "Certificaciones BMS",
    "elnet-certifications": "Certificaciones ElNet",
    "plc-ddc-controllers": "Controladores PLC y DDC",
    "parking-control": "Control de estacionamientos",
    "plumbing-control": "Control de fontanería",
    "flood-detection-systems": "Sistemas de detección de inundaciones",
    "flooding-sensor": "Sensor de inundación",
    "bms-scada-software": "Software BMS / SCADA",
    "transfer-switches": "Interruptores de transferencia",
    "power-factor-control": "Control de factor de potencia",
    "smart-parking": "Estacionamiento inteligente",
    "co-gas-monitoring": "Monitoreo de gas CO",
    "power-quality-analyzers": "Analizadores de calidad de energía",
    "energy-meters": "Medidores de energía",
    "electrical-meters": "Medidores eléctricos",
    "elnet-billing-software": "Software de facturación ElNet",
    "public-buildings": "Edificios públicos",
    "hospitals": "Hospitales",
    "hotels": "Hoteles",
    "universities": "Universidades",
    "museums": "Museos",
    "shopping-malls": "Centros comerciales",
    "industrial-hi-tech": "Industrial y alta tecnología",
    "pharmaceutical-clean-rooms": "Farmacéutica y salas limpias",
    "uniart-software": "Software UniArt",
    "uniweb-software": "Software UniWeb",
    "digipoint-controller": "Controlador DigiPoint",
    "veropoint-controller": "Controlador VeroPoint",
    "superbrain-controller": "Controlador SuperBrain",
    "superbrain-dr-controller": "Controlador SuperBrain DR",
    "superbrain-fc-controller": "Controlador SuperBrain FC",
    "elnet-mc-1-meter": "Medidor ElNet MC-1",
    "elnet-mc-2-meter": "Medidor ElNet MC-2",
    "elnet-mc-8-meter": "Medidor ElNet MC-8",
    "elnet-mc-12-meter": "Medidor ElNet MC-12",
    "elnet-co-transfer-switch": "Interruptor de transferencia ElNet CO",
    "elnet-cod-transfer-switch": "Interruptor de transferencia ElNet COD",
    "elnet-pfc-controller": "Controlador ElNet PFC",
    "elnet-ltc-controller": "Controlador ElNet LTC",
    "elnet-ltc10-controller": "Controlador ElNet LTC10",
    "elnet-va-meter": "Medidor ElNet VA",
    "elnet-vip-meter": "Medidor ElNet VIP",
    "elnet-pic-meter": "Medidor ElNet PIC",
    "elnet-lte-meter": "Medidor ElNet LTE",
    "elnet-lt-meter": "Medidor ElNet LT",
    "elnet-ltp-meter": "Medidor ElNet LTP",
    "elnet-pq-gr-meter": "Medidor ElNet PQ/GR",
    "elnet-xp-controller": "Controlador ElNet XP",
}

CANONICAL_SLUG_SET = frozenset(CANONICAL_SLUGS)


def canonical_slug(slug: str) -> str:
    if not slug:
        return ""
    slug = slug.strip()
    return slug if slug in CANONICAL_SLUG_SET else slug


def all_canonical_slugs() -> list[str]:
    return list(CANONICAL_SLUGS)


def resolve_source_file(lang: str, canonical: str, content_dir) -> str | None:
    """Return JSON filename stem for a canonical page in a language."""
    if canonical == "":
        return "index" if (content_dir / "index.json").exists() else None
    path = content_dir / f"{canonical}.json"
    if path.exists():
        return canonical
    return None
