#!/usr/bin/env bash
# Stage cms apps for Firebase Hosting (flattens workspace deps into each app).
set -euo pipefail
ROOT="$(cd "$(dirname "$0")/.." && pwd)"
CMS="$ROOT/cms"
STAGE="$ROOT/.firebase-cms-stage"
rm -rf "$STAGE"
mkdir -p "$STAGE/web" "$STAGE/admin" "$STAGE/db"

echo "Copying @ddc/db…"
rsync -a --delete \
  --exclude node_modules --exclude dist \
  "$CMS/packages/db/" "$STAGE/db/"

stage_app() {
  local app="$1"
  local dest="$STAGE/$app"
  rsync -a --delete \
    --exclude node_modules --exclude .next --exclude .env.local --exclude .env \
    "$CMS/apps/$app/" "$dest/"

  # Vendor @ddc/db inside the app so Cloud Functions packaging keeps it
  # (file:../db breaks — Firebase only uploads the app folder into functions/).
  mkdir -p "$dest/vendor"
  rsync -a --delete \
    --exclude node_modules --exclude dist \
    "$CMS/packages/db/" "$dest/vendor/db/"

  node -e "
    const fs=require('fs');
    const p='$dest/package.json';
    const j=JSON.parse(fs.readFileSync(p,'utf8'));
    j.dependencies=j.dependencies||{};
    j.dependencies['@ddc/db']='file:./vendor/db';
    j.dependencies['@electric-sql/pglite']=j.dependencies['@electric-sql/pglite']||'^0.2.17';
    j.dependencies['drizzle-orm']=j.dependencies['drizzle-orm']||'^0.39.3';
    j.dependencies['postgres']=j.dependencies['postgres']||'^3.4.5';
    j.dependencies['dotenv']=j.dependencies['dotenv']||'^16.4.7';
    j.dependencies['firebase-admin']=j.dependencies['firebase-admin']||'^13.0.2';
    // Firebase Hosting frameworks runs npm install + next build in this folder
    j.scripts=j.scripts||{};
    j.scripts.build='next build';
    fs.writeFileSync(p, JSON.stringify(j,null,2)+'\n');
  "

  if [[ -f "$CMS/.env" ]]; then
    cp "$CMS/.env" "$dest/.env"
    cp "$CMS/.env" "$dest/.env.production"
    if [[ "$app" == "admin" ]]; then
      node -e "
        const fs=require('fs');
        const env=fs.readFileSync('$CMS/.env','utf8');
        const get=(k)=>{const m=env.match(new RegExp('^'+k+'=(.*)$','m'));return (m&&m[1]||'').trim();};
          const u=get('ADMIN_USERNAME')||'AdminDDC';
          const p=get('ADMIN_PASSWORD')||'6474998';
          const s=get('SESSION_SECRET')||'ddc-session-secret-change-in-prod-2026';
          const owner=get('ADMIN_OWNER_EMAIL')||'';
          const file='$dest/src/lib/credentials.server.ts';
          fs.writeFileSync(file, [
            '/** Generated by stage_cms_for_firebase.sh — do not edit by hand in stage. */',
            'export const username = ' + JSON.stringify(u) + ';',
            'export const password = ' + JSON.stringify(p) + ';',
            'export const sessionSecret = ' + JSON.stringify(s) + ';',
            'export const ownerEmail = ' + JSON.stringify(owner) + ';',
            ''
          ].join('\\n'));
        fs.writeFileSync('$dest/credentials.json', JSON.stringify({username:u,password:p,sessionSecret:s},null,2));
      "
    fi
  fi

  mkdir -p "$dest/data"
  cp "$CMS/data/public.json" "$dest/data/public.json"
  if [[ "$app" == "admin" ]]; then
    mkdir -p "$dest/src/data"
    cp "$CMS/data/public.json" "$dest/src/data/public.json"
    # Force in-memory PGlite on Firebase
    echo "PGLITE_MEMORY=1" >> "$dest/.env"
    echo "PGLITE_MEMORY=1" >> "$dest/.env.production"
  fi
  if [[ "$app" == "web" ]]; then
    mkdir -p "$dest/public/cms"
    cp "$CMS/data/public.json" "$dest/public/cms/public.json"
    if [[ -d "$ROOT/assets" ]]; then
      rm -rf "$dest/public/assets"
      mkdir -p "$dest/public"
      cp -R "$ROOT/assets" "$dest/public/assets"
    fi
  fi
  echo "Staged $app → $dest"
}

stage_app web
stage_app admin
echo "Done. Stage at $STAGE"
